# 10% data sample configuration

data:
  sample_size: 0.1  # Use 10% of data

# Reduce model complexity for faster experimentation
models:
  collaborative:
    neighborhood:
      k_neighbors: 10

    matrix_fact:
      n_factors: 20
      n_epochs: 10

# Simplify evaluation for faster results
evaluation:
  cv_folds: 3
  k_values: [5, 10]